In [12]:
import numpy as np
from numpy.linalg import inv
from numpy import linalg as LA

## Assume we have $10$ samples and $3$ features

In [5]:
T = 10
K = 3

In [6]:
Y_train = np.random.random((T, 1)) ## label

In [7]:
X_train = np.random.random((T, 3)) ## input size

## Ridge Regression V1：

Assuming $Y_{label}$ is training label in a form of column: $T \times 1$,
$X_{train}$ is training data in the form of matrix: $T \times K$, where
$K$ is the number of features.

### Step 1: transpose $Y_{train}$

Transpose $Y_{train}$: now $Y_train$ is in the form of $1 \times T$.

In [8]:
Y_train = Y_train.T

In [11]:
Y_train

array([[0.56695233, 0.31128824, 0.65813732, 0.83962923, 0.15307415,
        0.98223933, 0.03117382, 0.17310121, 0.1839843 , 0.76064966]])

In [10]:
X_train

array([[0.50171174, 0.30910614, 0.87895083],
       [0.6375385 , 0.47648357, 0.99828598],
       [0.48084943, 0.79951097, 0.89499244],
       [0.15048445, 0.59450423, 0.51427583],
       [0.38921102, 0.11179432, 0.83694569],
       [0.57801698, 0.71158913, 0.54137334],
       [0.52824316, 0.21939067, 0.39053698],
       [0.93541971, 0.39352621, 0.51080596],
       [0.63849549, 0.44045141, 0.48047649],
       [0.44853575, 0.91723251, 0.71851558]])

### Step 2: Create $K$ matrix in the form of $T \times T$

Assuming we declare a penalty $\alpha$

In [ ]:
def guassian_kernel(x, y, gamma):
    ## TODO: NORM
    return np.exp(-gamma * LA.norm(x - y)**2)

In [13]:
K_matrix = np.zeros((T, T))
alpha = 0.1

for s in range(T):
    for t in range(T):
        K_matrix[s, t] = np.dot(X_train[s,:], X_train[t,:])

In [15]:
K_matrix.shape

(10, 10)

In [21]:
additive_term = np.eye(T) * alpha

K_matrix = K_matrix + additive_term

In [23]:
K_matrix = inv(K_matrix)

### Step 3: Construct k in the form $T \times 1$

$x_{input}$ is the new batch, we want to make prediction.

In [26]:
x_input = np.random.random((K))

In [27]:
k = np.zeros((T, 1))

In [28]:
for t in range(T):
    k[t] = np.dot(X_train[t, :], x_input)

### Final Step: find $w \cdot x$：

In [29]:
result = np.matmul(np.matmul(Y_train, K_matrix), k)

In [30]:
result

array([[0.03462727]])

As you could the see the result is a number, which means we successfully predict a new
value with training data.

However, this approach is very naive and incomplete. We will have to go back and
calculate the corresponding Lagrange Multiplier and then find the weights explicitly because we
have infinity possibility to compute weights otherwise.

Also, we haven't really implement kernel method. I believe we could replace the dot product
with kernel method. This will extend ridge regression to KRR.

I view the single output as failure because we will need to take advantage of parallelism, which I will
read the spec for np.dot() carefully and make sure our project have the feature.

Lastly, as you see, the inverse is very expensive. We will optimize it.

Otherwise, this V1 is a good place to demonstrate the algorithm which I will keep it.