In [1]:
from KRR import KRR as KRR
import numpy as np

In [2]:
x_data = np.ones((100, 10))

In [3]:
Y_data = np.random.randint(0, 10, 100).reshape(100, 1)

In [7]:
Y_data

array([[6],
       [2],
       [3],
       [6],
       [7],
       [2],
       [0],
       [1],
       [9],
       [6],
       [3],
       [1],
       [4],
       [5],
       [8],
       [0],
       [8],
       [7],
       [4],
       [6],
       [8],
       [9],
       [2],
       [7],
       [4],
       [8],
       [6],
       [8],
       [9],
       [0],
       [4],
       [5],
       [2],
       [7],
       [5],
       [4],
       [9],
       [0],
       [3],
       [6],
       [9],
       [9],
       [8],
       [9],
       [2],
       [9],
       [2],
       [7],
       [6],
       [5],
       [4],
       [8],
       [4],
       [2],
       [4],
       [1],
       [9],
       [9],
       [3],
       [9],
       [7],
       [2],
       [6],
       [5],
       [5],
       [1],
       [5],
       [2],
       [6],
       [9],
       [3],
       [0],
       [1],
       [2],
       [5],
       [5],
       [5],
       [5],
       [3],
       [3],
       [9],
       [6],
       [4],
    

In [4]:
KRR_ME = KRR(x_data, Y_data, 'rbf', 0.5)

In [5]:
KRR_ME.gram

array([[7.12457641e-218, 2.06115362e-009, 1.80485139e-035, ...,
        6.71418429e-079, 2.03223080e-313, 2.06115362e-009],
       [7.12457641e-218, 2.06115362e-009, 1.80485139e-035, ...,
        6.71418429e-079, 2.03223080e-313, 2.06115362e-009],
       [7.12457641e-218, 2.06115362e-009, 1.80485139e-035, ...,
        6.71418429e-079, 2.03223080e-313, 2.06115362e-009],
       ...,
       [7.12457641e-218, 2.06115362e-009, 1.80485139e-035, ...,
        6.71418429e-079, 2.03223080e-313, 2.06115362e-009],
       [7.12457641e-218, 2.06115362e-009, 1.80485139e-035, ...,
        6.71418429e-079, 2.03223080e-313, 2.06115362e-009],
       [7.12457641e-218, 2.06115362e-009, 1.80485139e-035, ...,
        6.71418429e-079, 2.03223080e-313, 2.06115362e-009]])

In [6]:
KRR_ME.predict(0.05, x_data)

(1, 100)
(100, 100)
(100, 100)


array([[2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001844, 2982.00001844,
        2982.00001844, 2982.00001844, 2982.00001